### ISSUE TITLE
[QUESTION] What is the memory requirement for celery-exporter?

### ISSUE THREAD

**Issue by paxw-panevo** [danihodovic/celery-exporter#194]
We have a docker service that's using the image `danihodovic/celery-exporter` 

We have a memory limit set for this service at 100M. However, we find that this celery-exporter service's memory use steadily climbs up and consistently around ~3m mark, this limit is reached and the celery-exporter service gets killed and starts again. So I was wondering how much memory is usually needed to be able to run this tool?

**Comment by danihodovic** [comment]
To be honest with you I don't know. I don't think we constrain the memory of the exporter in our environment. Maybe @adinhodovic can fill you in.

**Comment by adinhodovic** [comment]
@paxw-panevo 
![image](https://user-images.githubusercontent.com/12065867/209343605-2d617cf9-5235-47c2-98a7-a068f4ebdd57.png)

Usage over 2 days, was upgraded before that. Yeah, I see a steady climb although not as consistent as you see and not as aggressive. Not sure why though, maybe we'll need restarts after x amount of memory built-in like Celery has in settings. Also, old metrics are not rotated out in the exporter atm (e.g workers going offline), our workers have static hostnames otherwise metrics cardinality becomes huge (each host/metrics has individual metrics) that sticks till the restart of the worker.

**Comment by danihodovic** [comment]
Merry Christmas and Happy New Year :santa:
